import time
import asyncio
import json
from typing import List, Dict, Any, Tuple, Optional
from sqlalchemy.orm import Session
from src.db import Lead, Analysis
from src.config import settings
from src.llm.client import build_llm
from src.llm.prompts import COLD_EMAIL_SYSTEM_PROMPT, COLD_EMAIL_USER_TEMPLATE
from src.utils.logging import logger

# Token pricing mapping per 1M input/output tokens (USD)
TOKEN_PRICING = {
    "claude-sonnet-4-6": {"input": 3.00, "output": 15.00},
    "gpt-5.4-mini": {"input": 0.15, "output": 0.60},
    "gemini-flash": {"input": 0.075, "output": 0.30},
    "default": {"input": 1.00, "output": 3.00}
}

def estimate_cost(model: str, input_chars: int, output_chars: int) -> float:
    # Estimate tokens: 1 token ~= 4 characters
    input_tokens = input_chars / 4.0
    output_tokens = output_chars / 4.0
    
    pricing = TOKEN_PRICING.get(model, TOKEN_PRICING["default"])
    cost = (input_tokens * pricing["input"] / 1_000_000) + (output_tokens * pricing["output"] / 1_000_000)
    return round(cost, 6)

async def run_model_comparison(
    db: Session,
    sample_size: int = 5,
    models: Optional[List[str]] = None
) -> List[Dict[str, Any]]:
    """
    Runs LLM bake-off:
    1. Selects N leads in 'analyzed' or 'drafted' status.
    2. Runs generation for each lead across all specified models.
    3. Measures latency, estimates costs, and compiles outputs side-by-side.
    """
    if not models:
        models = [
            "claude-sonnet-4-6:anthropic",
            "gpt-5.4-mini:openai",
            "gemini-flash:google"
        ]

    # Query leads
    leads = db.query(Lead).filter(Lead.status.in_(["analyzed", "drafted"])).limit(sample_size).all()
    if not leads:
        logger.warning("No analyzed or drafted leads found in the database to run bake-off.")
        return []

    comparison_results = []

    for lead in leads:
        analysis = lead.analysis
        if not analysis or not analysis.service_map:
            continue
            
        evidence_list = [entry["evidence"] for entry in analysis.service_map.values()]
        findings_str = "\n".join(f"- {ev}" for ev in evidence_list)
        
        lead_runs = []
        for model_prov in models:
            if ":" in model_prov:
                model_name, provider_name = model_prov.split(":", 1)
            else:
                model_name = model_prov
                provider_name = "anthropic"  # default fallback
                
            api_key = settings.anthropic_api_key or settings.openai_api_key or settings.google_api_key
            
            start_time = time.time()
            subject = ""
            body = ""
            
            # If mock, simulate outputs to show visual comparisons in CLI/UI
            if not api_key or api_key == "mock-key":
                # Simulated delay and output
                await asyncio.sleep(0.5)
                latency = round(time.time() - start_time, 2)
                subject = f"[Mock {model_name}] Custom Subject Line"
                body = f"Hi {lead.name or 'there'},\n\nThis is a mock draft generated by {model_name} citing:\n{findings_str}"
                cost = estimate_cost(model_name, len(findings_str), len(body))
            else:
                try:
                    llm = build_llm(model=model_name, provider=provider_name)
                    
                    user_prompt = COLD_EMAIL_USER_TEMPLATE.format(
                        lead_name=lead.name or "Website Owner",
                        business=lead.name or lead.domain,
                        website_url=lead.website_url,
                        findings=findings_str,
                        cta=settings.email.cta
                    )
                    
                    messages = [
                        {"role": "system", "content": COLD_EMAIL_SYSTEM_PROMPT},
                        {"role": "user", "content": user_prompt}
                    ]
                    
                    response = await llm.ainvoke(messages)
                    content = response.content.strip()
                    
                    # Clean json code block wrap
                    if content.startswith("```json"):
                        content = content[7:]
                    if content.endswith("```"):
                        content = content[:-3]
                    content = content.strip()
                    
                    email_json = json.loads(content)
                    subject = email_json.get("subject", "").strip()
                    body = email_json.get("body", "").strip()
                    latency = round(time.time() - start_time, 2)
                    cost = estimate_cost(model_name, len(user_prompt), len(body))
                except Exception as e:
                    logger.error("Bake-off model run failed", model=model_name, error=str(e))
                    subject = "Error"
                    body = f"Model execution failed: {str(e)}"
                    latency = round(time.time() - start_time, 2)
                    cost = 0.0
            
            lead_runs.append({
                "model": model_name,
                "provider": provider_name,
                "subject": subject,
                "body": body,
                "latency_s": latency,
                "estimated_cost_usd": cost
            })
            
        comparison_results.append({
            "lead_id": lead.id,
            "lead_name": lead.name,
            "website_url": lead.website_url,
            "runs": lead_runs
        })
        
    return comparison_results
